site_name: QGIS GeoNode QGIS Plugin

repo_url: https://github.com/kartoza/qgis_geonode
repo_name: qgis_geonode

site_description: QGIS GeoNode plugin

site_author: Kartoza

nav:
  - Home: 'index.md'
  - User guide: 'user-guide.md'
  - Development: 'development.md'
  - About: 'about.md'
  - Changelog: 'changelog-base.md'
  - QGIS Repo: 'repo/plugins.xml'
  - QEP - Remove QGIS core GeoNode support: 'qep-remove-core-geonode-support.md'

theme:
  name: material
  palette:
    primary: green
    accent: purple
    scheme: preference
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.snippets:
      base_path: .
  - admonition

plugins:
  - search
