site_name: QGIS GeoNode QGIS Plugin

repo_url: https://github.com/kartoza/qgis_geonode
repo_name: qgis_geonode

site_description: QGIS GeoNode plugin

site_author: Kartoza

nav:
  - Home: 'index.md'
  - About: 'about.md'
  - User guide: 'user-guide.md'
  - Development: 'development.md'
  - QGIS Repo: 'repo/plugins.xml'

theme:
  name: material
  palette:
    primary: green
    accent: purple
    scheme: preference
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
  icon:
    - repo: fontawesome/brands/github

markdown_extensions:
  - toc:
      permalink: true

plugins:
  - search
