[tool.poetry]
name = "qgis_geonode"
version = "0.1.0"
description = "A QGIS plugin for integrating with GeoNode"
authors = ["Kartoza <info@kartoza.com>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.8"
toml = "^0.10.2"
typer = "^0.3.2"
ipython = "^7.19.0"
pytest = "^6.2.1"
pytest-qt = "^3.3.0"
black = {version = "^20.8b1", allow-prereleases = true}
flask = "^1.1.2"

[tool.poetry.dev-dependencies]

[tool.qgis-plugin.metadata]
name = "QGIS GeoNode"
qgisMinimumVersion = "3.10"
icon = "mIconGeonode.svg"
experimental = "True"
deprecated = "False"
homepage = "https://github.com/kartoza/qgis_geonode"
tracker = "https://github.com/kartoza/qgis_geonode/issues"
repository = "https://github.com/kartoza/qgis_geonode"
tags = [
    "geonode",
]
category = "plugins"
hasProcessingProvider = "no"
about = "This plugin has an about here"
# changelog: dynamically pulled from the README.md file
# description: dynamically pulled from the tool.poetry.description section
# version: dynamically pulled from the tool.poetry.version section
# author: dynamically pulled from the tool.poetry.authors section
# email: dynamically pulled from the tool.poetry.authors section
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

