# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QgisGeoNode
                                 A QGIS plugin
 A QGIS plugin that provides integration with GeoNode
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-12-23
        copyright            : (C) 2020 by Kartoza
        email                : info@kartoza.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
from qgis_geonode.apiclient.apiv2 import GeonodeApiV2Client
from qgis_geonode.apiclient.csw import GeonodeLegacyClient
from qgis_geonode.conf import ConnectionSettings


def classFactory(iface):  # pylint: disable=invalid-name
    """Load QgisGeoNode class from file QgisGeoNode.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .main import QgisGeoNode

    return QgisGeoNode(iface)
