name: qgis_geonode CI

on: push

jobs:
  ci:
    runs-on: ubuntu-20.04
    container:
      image: qgis/qgis:release-3_16
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: check where we are
        run: echo $(ls /)
        shell: bash
      - name: Install poetry
        uses: Gr1N/setup-poetry@v4
      - name: Install pluginadmin dependencies
        run: poetry install
      - name: Check formatting
        run: poetry run black --check src/qgis_geonode