name: Rebuild docs
on: workflow_dispatch

jobs:

  rebuild-docs:
    runs-on: ubuntu-22.04
    container:
      image: qgis/qgis:final-3_34_12
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: fix Python command
        run: apt-get install python-is-python3

      - name: Install poetry
        uses: Gr1N/setup-poetry@v8

      - name: Install pluginadmin dependencies
        run: poetry install

      - name: generate plugin repo XML
        run: poetry run python pluginadmin.py --verbose generate-plugin-repo-xml

      - name: update docs
        run: |
          git config --global --add safe.directory '*'
          poetry run mkdocs gh-deploy --force